open_traffic:
  target: dev
  outputs:
    dev:
      type: postgres
      host: host.docker.internal
      user: airflow
      pass: airflow
      port: 5432
      dbname: airflow
      schema: public
      threads: 4