
version: 2

models:
  - name: open_traffic_details
    description: "An open traffic dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
